---
# https://github.com/geerlingguy/ansible-role-dotfiles/issues/11
- name: geerlingguy.dotfiles
  src: https://github.com/oxyc/ansible-role-dotfiles.git
  version: issue-11
- name: geerlingguy.homebrew
- name: geerlingguy.mas
- name: fubarhouse.macdock
